apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-java-springboot-basic-rhtap-devfile-multi-c-yhzy
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/e2e-demos-yxrf-tenant/mc-two-scenarios/devfile-sample-java-springboot-basic-rhtap-devfile-multi-c-yhzy@sha256:aad64c3dbeb1047e3d32bc28625e6e00ce58ab66a4abd18cfe43ae493e51aa02
        name: my-java-springboot
        resources: {}
status: {}
